project_id = "lzqlsanwgvftearaiast"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_captcha_enabled = false
security_update_password_require_reauthentication = false

[rest]
enabled = true
port = 54329

[realtime]
enabled = true
port = 54330

[edge_runtime]
enabled = true
port = 54331

[functions.connect-exchange]
verify_jwt = true

[functions.sync-exchange-balances]
verify_jwt = true

[functions.arbitrage-quotes]
verify_jwt = true

[functions.arbitrage-execute]
verify_jwt = true

[functions.arbitrage-scanner]
verify_jwt = false

[functions.flash-loan-execute]
verify_jwt = false
